// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/go-logr/logr"
	"github.com/golang/mock/gomock"
	"github.com/kubemod/kubemod/expressions"
	"github.com/kubemod/kubemod/mocks"
	"github.com/kubemod/kubemod/util"
)

// Injectors from wire.go:

// InitializeModRuleStoreTestBed instructs wire how to construct a new test bed.
func InitializeModRuleStoreTestBed(clusterModRulesNamespace ClusterModRulesNamespace, tLogger util.TLogger) *ModRuleStoreTestBed {
	language := expressions.NewKubeModJSONPathLanguage()
	logger := NewTestLogger(tLogger)
	modRuleStoreItemFactory := NewModRuleStoreItemFactory(language, logger)
	modRuleStore := NewModRuleStore(modRuleStoreItemFactory, clusterModRulesNamespace, logger)
	modRuleStoreTestBed := NewModRuleStoreTestBed(modRuleStore)
	return modRuleStoreTestBed
}

// InitializeDragnetWebhookHandlerTestBed instructs wire how to construct a new test bed.
func InitializeDragnetWebhookHandlerTestBed(clusterModRulesNamespace ClusterModRulesNamespace, tLogger util.TLogger) *DragnetWebhookHandlerTestBed {
	language := expressions.NewKubeModJSONPathLanguage()
	logger := NewTestLogger(tLogger)
	modRuleStoreItemFactory := NewModRuleStoreItemFactory(language, logger)
	modRuleStore := NewModRuleStore(modRuleStoreItemFactory, clusterModRulesNamespace, logger)
	testReporter := NewMockTestReporter(tLogger)
	controller := NewGoMockController(testReporter)
	mockClient := NewK8sMockClient(controller)
	dragnetWebhookHandlerTestBed := NewDragnetWebhookHandlerTestBed(modRuleStore, controller, mockClient, logger)
	return dragnetWebhookHandlerTestBed
}

// InitializeModRuleStoreItemTestBed instructs wire how to construct a new test bed.
func InitializeModRuleStoreItemTestBed(tLogger util.TLogger) *ModRuleStoreItemTestBed {
	language := expressions.NewKubeModJSONPathLanguage()
	logger := NewTestLogger(tLogger)
	modRuleStoreItemFactory := NewModRuleStoreItemFactory(language, logger)
	modRuleStoreItemTestBed := NewModRuleStoreItemTestBed(modRuleStoreItemFactory)
	return modRuleStoreItemTestBed
}

// wire.go:

// ModRuleStoreTestBed is a structure used to provide services for ModRuleStore tests.
type ModRuleStoreTestBed struct {
	modRuleStore *ModRuleStore
}

// ModRuleStoreItemTestBed is used in ModRuleStoreItem test.
type ModRuleStoreItemTestBed struct {
	itemFactory *ModRuleStoreItemFactory
}

// DragnetWebhookHandlerTestBed is used in DragnetWebhookHandler test.
type DragnetWebhookHandlerTestBed struct {
	mockCtrl      *gomock.Controller
	mockK8sClient *mocks.MockClient
	modRuleStore  *ModRuleStore
	log           logr.Logger
}

// NewLogger instantiates a new testing logger.
func NewTestLogger(tLogger util.TLogger) logr.Logger {
	return util.TestLogger{TLogger: tLogger}
}

// NewMockTestReporter converts a TLogger to gomock.TestReporter.
func NewMockTestReporter(tLogger util.TLogger) gomock.TestReporter {
	return tLogger
}

// NewGoMockController instantiates a new mock controller.
func NewGoMockController(testReporter gomock.TestReporter) *gomock.Controller {
	return gomock.NewController(testReporter)
}

// NewK8sMockClient instantiates a new K8S client mock.
func NewK8sMockClient(mockCtrl *gomock.Controller) *mocks.MockClient {
	return mocks.NewMockClient(mockCtrl)
}

// NewModRuleStoreTestBed instantiates a new test bed.
func NewModRuleStoreTestBed(modRuleStore *ModRuleStore) *ModRuleStoreTestBed {
	return &ModRuleStoreTestBed{
		modRuleStore: modRuleStore,
	}
}

// NewModRuleStoreItemTestBed instantiates a new test bed.
func NewModRuleStoreItemTestBed(itemFactory *ModRuleStoreItemFactory) *ModRuleStoreItemTestBed {
	return &ModRuleStoreItemTestBed{
		itemFactory: itemFactory,
	}
}

// NewDragnetWebhookHandlerTestBed instantiates a new test bed.
func NewDragnetWebhookHandlerTestBed(modRuleStore *ModRuleStore, mockCtrl *gomock.Controller, mockK8sClient *mocks.MockClient, log logr.Logger) *DragnetWebhookHandlerTestBed {
	return &DragnetWebhookHandlerTestBed{
		mockCtrl:      mockCtrl,
		mockK8sClient: mockK8sClient,
		modRuleStore:  modRuleStore,
		log:           log,
	}
}
