// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/kubemod/kubemod/controllers"
	"github.com/kubemod/kubemod/core"
	"github.com/kubemod/kubemod/expressions"
	"k8s.io/apimachinery/pkg/runtime"
)

// Injectors from wire.go:

func InitializeKubeModApp(scheme *runtime.Scheme, metricsAddr string, enableLeaderElection EnableLeaderElection, enableDevModeLog EnableDevModeLog) (*KubeModApp, error) {
	logger := NewLogger(enableDevModeLog)
	manager, err := NewControllerManager(scheme, metricsAddr, enableLeaderElection, logger)
	if err != nil {
		return nil, err
	}
	language := expressions.NewJSONPathLanguage()
	modRuleStoreItemFactory := core.NewModRuleStoreItemFactory(language, logger)
	modRuleStore := core.NewModRuleStore(modRuleStoreItemFactory, logger)
	modRuleReconciler, err := controllers.NewModRuleReconciler(manager, modRuleStore, logger)
	if err != nil {
		return nil, err
	}
	dragnetWebhookHandler := core.NewDragnetWebhookHandler(manager, modRuleStore, logger)
	kubeModApp, err := NewKubeModApp(scheme, manager, modRuleReconciler, dragnetWebhookHandler, logger)
	if err != nil {
		return nil, err
	}
	return kubeModApp, nil
}

// wire.go:

type EnableLeaderElection bool

type EnableDevModeLog bool
