apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        admission.kubemod.io/enable-node-synthetic-ref: "true"
        node.alpha.kubernetes.io/ttl: ""
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
          - name: INJECTED_NODE_TTL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['node.alpha.kubernetes.io/ttl']
