apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # Turning on node synthetic ref will make KubeMod monitor for pod scheduling events.
        # When the pod gets scheduled, KubeMod injects a synthetic ref to the pod's node
        # and triggers all UPDATE modrules that match this pod.
        admission.kubemod.io/enable-node-synthetic-ref: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
          - name: INJECTED_NODE_TTL
            valueFrom:
              fieldRef:
                # The following annotation will be populated by modrule-7.
                fieldPath: metadata.annotations['node.alpha.kubernetes.io/ttl']
