apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: patch-clusterrole
  namespace: kubemod-system
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: 'ClusterRole'

    - select: '$.metadata.name'
      matchValue: 'my-clusterrole'

  patch:
    - op: add
      path: /metadata/labels/color
      value: blue
