apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: modrule-1
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: 'Deployment'

    - select: '$.metadata.labels.app'
      matchValue: 'nginx'

    # Find deployments which include an nginx 1.14 container...
    - select: '$.spec.template.spec.containers[*].image'
      matchRegex: 'nginx:1\.14\..*'
    
  patch:
    - op: add
      path: /metadata/labels/color
      value: whatever

    # Force their container port to be 8080
    - op: add
      path: /spec/template/spec/containers/0/ports
      value: |-
        - containerPort: 8080
          protocol: TCP
