apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: patch-pod-with-node-annotations
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"

  match:
    - select: '$.syntheticRefs.node.metadata.annotations["node.alpha.kubernetes.io/ttl"]'

    - select: '$.kind'
      matchValue: 'Pod'

  patch:
    - op: add
      path: /metadata/annotations/node.alpha.kubernetes.io~1ttl
      value: '"{{ index .Target.syntheticRefs.node.metadata.annotations "node.alpha.kubernetes.io/ttl"}}"'
