apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: modrule-1
spec:
  type: Patch

  match:
    - select: '$.kind'
      matchValue: 'Deployment'

    - select: '$.metadata.labels.app'
      matchValue: 'nginx'

    # Find deployments which include an nginx 1.14 container...
    - select: '$.spec.template.spec.containers[*].image'
      matchRegex: 'nginx:1\.14\..*'
    
  patch:
    - op: add
      path: /metadata/labels/color
      value: whatever

    # Change all nginx containers' ports from 80 to 8080
    - op: add
      select: $.spec.template.spec.containers[? @.image =~ "nginx" ].ports[? @.containerPort == 80]
      path: /spec/template/spec/containers/#0/ports/#1/containerPort
      value: '8080'
