apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: reject-namespace-deletion
  namespace: kubemod-system
spec:
  type: Reject
  operation:
    - DELETE

  rejectMessage: 'deletion of protected namespaces is not allowed'

  match:
    - select: '$.kind'
      matchValue: 'Namespace'

    - select: '$.metadata.labels.protected =~ "yes"'
