apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: reject-malicious-services
spec:
  type: Reject

  match:
    - select: '$.kind'
      matchValue: 'Service'

    - select: '$.kind'
      matchValue: 'Service'

    - select: '$.spec.externalIPs[?@ !~ "123\\.12\\.34\\..*"]'
