name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.7'

    - uses: actions/checkout@v2

    - name: Test
      run: make test
