name: 'CI Test Workflow'

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Whatever
      run: echo ${{ github.ref }}

    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.7'

    - uses: actions/checkout@v2

    - name: Test
      run: make test

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: 'github.ref'
