name: 'Master Workflow'

on:
  push:
    branches:
      - 'master'

jobs:

  deploy:
    name: Test and deploy latest master
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false

    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'

      - uses: actions/checkout@v2


      - name: Deploy Latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBEMOD_IMAGE_VERSION: latest

        run: |
          ./build/deploy-image.sh
          bash <(curl -s https://codecov.io/bash)
