name: 'Tag Workflow'

on:
  push:
    tags:
      - 'v*'

jobs:

  deploy_tag:
    name: Test and deploy tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.7'

      - uses: actions/checkout@v2

      - name: Deploy Tag
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: ./build/deploy-image.sh
