name: 'Pull Request Workflow'

on:
  pull_request:

jobs:

  test:
    name: Test pull request
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false

    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.7'

      - uses: actions/checkout@v2

      - name: Test
        run: |
          make test
          bash <(curl -s https://codecov.io/bash)
